name: CatReps
version: 2020.04.08
date: 08/04/2020
description: Representations and cohomology of finite categories

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Tibor Grün
      url: https://github.com/Tschitschibor
    - name: Peter Webb
      url: https://www-users.math.umn.edu/~webb

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Tibor Grün
      url: https://github.com/Tschitschibor
    - name: Peter Webb
      url: https://www-users.math.umn.edu/~webb

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2020.02.16"
      url: "http://homalg-project.github.io/CAP_project/CAP/"
    - name: "FinSetsForCAP"
      version: ">= 2019.12.19"
      url: "https://github.com/homalg-project/FinSetsForCAP/"
    - name: "CategoryConstructor"
      version: ">= 2020.04.06"
      url: "https://github.com/homalg-project/CategoryConstructor"
    - name: "SubcategoriesForCAP"
      version: ">= 2020.02.02"
      url: "https://github.com/homalg-project/SubcategoriesForCAP/"
    - name: "MatricesForHomalg"
      version: ">= 2020.02.02"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "Toposes"
      version: ">= 2020.02.19"
      url: "https://github.com/homalg-project/Toposes"
    - name: "FunctorCategories"
      version: ">= 2020.04.08"
      url: "https://github.com/homalg-project/FunctorCategories/"

www: https://homalg-project.github.io/CatReps
readme: README.md
packageinfo: https://homalg-project.github.io/CatReps/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/CatReps/releases/download/v2020.04.08/CatReps-2020.04.08.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
