name: CatReps
version: "2020.05.20"
date: 2020-05-20
description: |
    Representations and cohomology of finite categories

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Tibor Grün
      url: https://github.com/Tschitschibor
    - name: Peter Webb
      url: https://www-users.math.umn.edu/~webb

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Tibor Grün
      url: https://github.com/Tschitschibor
    - name: Peter Webb
      url: https://www-users.math.umn.edu/~webb

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2020.04.27"
      url: "https://homalg-project.github.io/CAP_project/CAP"
    - name: "FinSetsForCAP"
      version: ">= 2020.04.01"
      url: "https://github.com/homalg-project/FinSetsForCAP/"
    - name: "CategoryConstructor"
      version: ">= 2020.04.15"
      url: "https://github.com/homalg-project/CategoryConstructor"
    - name: "SubcategoriesForCAP"
      version: ">= 2020.04.07"
      url: "https://github.com/homalg-project/SubcategoriesForCAP/"
    - name: "MatricesForHomalg"
      version: ">= 2020.02.02"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "Toposes"
      version: ">= 2020.04.27"
      url: "https://github.com/homalg-project/Toposes"
    - name: "Algebroids"
      version: ">= 2020.04.24"
      url: "https://github.com/homalg-project/Algebroids/"
    - name: "FunctorCategories"
      version: ">= 2020.05.20"
      url: "https://github.com/homalg-project/FunctorCategories/"

www: https://homalg-project.github.io/CatReps
readme: README.md
packageinfo: https://homalg-project.github.io/CatReps/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/CatReps/releases/download/v2020.05.20/CatReps-2020.05.20.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    finite categories, concrete categories, representations of categories.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BGW20</span>]   <b class='BibAuthor'>Barakat, M., Grün, T. and Webb, P.</b>,
     <i class='BibTitle'>CatReps, Representations and cohomology of finite categories,
             Version 2020.05.20</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/CatReps">https://homalg-project.github.io/CatReps</a></span>.
    </p>
    

bibtex: |
    @misc{ CatReps2020.05.20,
      author =           {Barakat, M. and Gr{\"u}n, T. and Webb, P.},
      title =            {{CatReps}, Representations and cohomology of finite categories, {V}ersion 2020.05.20},
      month =            {May},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://homalg-project.github.io/CatReps} {\texttt{https://homalg-project.github.io/}\discretionary {}{}{}\texttt{CatReps}}},
      keywords =         {finite categories, concrete categories, representations of categories},
      printedkey =       {BGW20}
    }

